### ISSUE TITLE
mindware website login/sign-up page not working

### ISSUE THREAD

**Issue by cojovi** [open-mindware/AutoGPT-Mindware#3]
when trying to sign up, it takes the input but doesnt send the confirmation email. i tried different email servers, nothing works.

**Comment by 0xtotaylor** [comment]
Thank you for raising, @cojovi. We recently transferred and migrated domains, which impacted our email service. You should be all set now!

**Comment by 0xtotaylor** [comment]
Thank you for raising, @cojovi. We recently transferred and migrated domains, which impacted our email service. You should be all set now!
